[env:ESP32-S3-RGB-Matrix]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.39
board = ESP32-S3-RGB-MATRIX
board_build.partitions = custom_partitions.csv
extra_scripts = pre:scripts/generate_headers.py
framework = arduino
monitor_speed = 115200

build_unflags =
	-D ARDUINO_LOOP_STACK_SIZE
build_flags =
	-D VERSION_MAJOR=1
	-D VERSION_MINOR=0
	-D WEBAPPVER_MAJOR=1
	-D WEBAPPVER_MINOR=0
	-D GITHUBAPIHOST='"api.github.com"'
	-D GITHUBTOKEN='""'
	-D GITHUBREPOPATH='"/repos/gadec-uk/matrix-departures-board/releases/latest"'
	-D BOARD_HAS_PSRAM
	-D CONFIG_SPIRAM_MODE_OCT
	-D DEFAULT_STORAGE_TYPE_ESP32=STORAGE_SD_MMC
	-D DEFAULT_FTP_SERVER_NETWORK_TYPE_ESP32=NETWORK_ESP32
	-D FTP_BUF_SIZE=512
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_LOOP_STACK_SIZE=16384
	-D NO_CIE1931
lib_deps =
	mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.15
	adafruit/Adafruit GFX Library@^1.12.6
	olikraus/U8g2_for_Adafruit_GFX@^1.8.0
	tzapu/WiFiManager@2.0.17
	bblanchon/ArduinoJson@7.2.2
  	ESP32Async/AsyncTCP@3.4.10
  	ESP32Async/ESPAsyncWebServer@3.10.0